Update README.md
verdaccio/docker-examples pull request #16
Opened 2018-12-08 19:07 UTC by weyert

Added a callout to the credentials to the README.md file

2018-12-08 22:37 UTC, sergiohgz requested changes
Only that, the rest :+1:

2018-12-08 22:37 UTC, sergiohgz commented on README.md
> +If you want to login into the Verdaccio instance creating via these Docker Examples, please try:
creating - > creat**ed**

2018-12-09 01:11 UTC, weyert commented
Updated :)

2018-12-09 11:15 UTC, sergiohgz requested changes
Minor change. Also, squash commits please.

2018-12-09 11:15 UTC, sergiohgz commented on README.md
> +
Sorry, I didn't show that this is the main README. This user-pass pair doesn't apply on all examples, As @juanpicado said in Discord, the README you should update is in _docker-local-storage-volume_ folder ([here](https://github.com/verdaccio/docker-examples/blob/master/docker-local-storage-volume/readme.md))

Also, there is other example that need this info, _https-portal-example_  ([here](https://github.com/verdaccio/docker-examples/blob/master/https-portal-example/README.md)). Please, can you add in this README also? Thanks :slightly_smiling_face:

2018-12-09 13:30 UTC, weyert commented
I have updated the text. I didn't get it to squash commits.

2018-12-09 15:04 UTC, sergiohgz approved these changes
👌 Perfect, thanks

2018-12-09 15:06 UTC, merged